---
name: "Publish to PyPI"

on:
  release:
    types: ["published"]

permissions:
  contents: "read"

jobs:
  build:
    name: "Build package"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"

      - name: "Install pypa/build"
        run: |
          python -m pip install build

      - name: "Build a binary wheel and a source tarball"
        run: |
          python -m build

      - name: "Upload release assets to GitHub"
        uses: "actions/upload-artifact@v4"
        with:
          name: "release-dists"
          path: "dist/*"

      - name: "Store the distribution packages"
        uses: "actions/upload-artifact@v4"
        with:
          name: "python-package-distributions"
          path: "dist/"

  pypi-publish:
    name: "Publish release to PyPI"
    needs: ["build"]
    runs-on: "ubuntu-latest"
    environment:
      name: "pypi"
      url: "https://pypi.org/p/pydsmc"
    permissions:
      id-token: "write"

    steps:
      - name: "Download all the dists"
        uses: "actions/download-artifact@v4"
        with:
          name: "release-dists"
          path: "dist/"

      - name: "Publish package to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          packages-dir: "dist/"
